<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>uuid</key>
        <string>7d281bff-dcdf-11e1-9b31-5404a604ef8a</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.double</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>text.plain</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:^[ \t]+)?(actor|participant)\s+(".*")\s+(as)\s+(\w+)\s+(.*)</string>
                <key>name</key>
                <string>meta.declaration</string>
            </dict>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>text.plain</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:^[ \t]+)?(actor|participant)\s+(\w+)\s*(.*)</string>
                <key>name</key>
                <string>meta.declaration</string>
            </dict>

            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>text.plain</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:^[ \t]+)?(title|loop|alt|else|opt|par|break|critical)\s+(.+)</string>
                <key>name</key>
                <string>meta.declaration</string>
            </dict>

            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:^[ \t]+)?(activate|deactivate|destroy)\s+(.+)</string>
                <key>name</key>
                <string>meta.declaration</string>
            </dict>

            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>text.plain</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:^[ \t]+)?(note)\s+(left|right|over)\s+(of\s+)?(.+)\s*:(.*)</string>
                <key>name</key>
                <string>meta.declaration</string>
            </dict>

            <dict>
                <key>begin</key>
                <string>(?:^[ \t]+)?(note)\s+(left|right|over)\s+(of\s+)?(.+)</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(?:^[ \t]+)?end note</string>
                <key>endCaptures</key>
                <dict>
                    <key>0</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                </dict>
                <key>name</key>
                <string>meta.note</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>.</string>
                        <key>name</key>
                        <string>text.plain</string>
                    </dict>
                </array>
            </dict>

            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.def</string>
                    </dict>
                    <key>3</key>
                    <dict>
                        <key>name</key>
                        <string>variable.language</string>
                    </dict>
                    <key>4</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.separator</string>
                    </dict>
                    <key>5</key>
                    <dict>
                        <key>name</key>
                        <string>text.plain</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>(?:^[ \t]+)?(\w+)\s*([-&gt;&lt;]+)\s*(\w+)\s*([:])?\s*(.*)?</string>
                <key>name</key>
                <string>meta.sequence</string>
            </dict>
            <dict>
                <key>name</key>
                <string>keyword.control.def</string>
                <key>match</key>
                <string>\b(?:autonumber|boxcreate|end|enduml|footbox|group|hide|newpage|skin|skinparam|startuml)\b</string>
            </dict>
        </array>
        <key>name</key>
        <string>Sequence Diagram</string>
        <key>scopeName</key>
        <string>text.sequence</string>
        <key>fileTypes</key>
        <array>
            <string>seq</string>
            <string>plant</string>
        </array>
    </dict>
</plist>
